### ISSUE TITLE
Error run_nichetoolbox()

### ISSUE THREAD

**Issue by vijaybarve** [luismurao/nichetoolbox#1]
Just installed and tried running the fxn run_nichetoolbox

```
 run_nichetoolbox()

Listening on http://127.0.0.1:5781
Warning in file(filename, "r", encoding = encoding) :
  cannot open file 'ui_layers/style': Permission denied
Warning: Error in file: cannot open the connection
Stack trace (innermost first):
    44: file
    43: FUN
    42: lapply
    41: sapply
     2: shiny::runApp
     1: run_nichetoolbox
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
```

**Comment by luismurao** [comment]
Hi Vijay,

I made a bug fix can you check if it works?
https://github.com/luismurao/nichetoolbox

2016-06-22 13:07 GMT-05:00 Vijay Barve notifications@github.com:

> Just installed and tried running the fxn run_nichetoolbox
> 
>  run_nichetoolbox()
> 
> Listening on http://127.0.0.1:5781
> Warning in file(filename, "r", encoding = encoding) :
>   cannot open file 'ui_layers/style': Permission denied
> Warning: Error in file: cannot open the connection
> Stack trace (innermost first):
>     44: file
>     43: FUN
>     42: lapply
>     41: sapply
>      2: shiny::runApp
>      1: run_nichetoolbox
> Error in file(filename, "r", encoding = encoding) :
>   cannot open the connection
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/luismurao/nichetoolbox/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/ARNKAYbv9DZZIZ63Cra7gB0_hWpxPCJsks5qOXnPgaJpZM4I8D4I
> .

## 

Luis

**Comment by vijaybarve** [comment]
Yes works now.
